'use strict';

module.exports = {
	'rules': {
		'selector-attribute-brackets-space-inside': ['never', { 'severity': 'warning' }],
		'selector-attribute-operator-blacklist': null,
		'selector-attribute-operator-space-after': ['never', { 'severity': 'warning' }],
		'selector-attribute-operator-space-before': ['never', { 'severity': 'warning' }],
		'selector-attribute-operator-whitelist': null,
		'selector-attribute-quotes': ['always', { 'severity': 'warning' }],
		'selector-class-pattern': null,
		'selector-combinator-space-after': null,
		'selector-combinator-space-before': null,
		'selector-descendant-combinator-no-non-space': true,
		'selector-id-pattern': null,
		'selector-max-compound-selectors': 3,
		'selector-max-specificity': ['0,3,2', { 'severity': 'warning' }],
		'selector-nested-pattern': null,
		'selector-no-attribute': null,
		'selector-no-combinator': null,
		'selector-no-empty': true,
		'selector-no-id': true,
		'selector-no-qualifying-type': true,
		'selector-no-type': null,
		'selector-no-universal': [true, { 'severity': 'warning' }],
		'selector-no-vendor-prefix': true,
		'selector-pseudo-class-blacklist': null,
		'selector-pseudo-class-case': 'lower',
		'selector-pseudo-class-no-unknown': true,
		'selector-pseudo-class-parentheses-space-inside': ['never', { 'severity': 'warning' }],
		'selector-pseudo-class-whitelist': null,
		'selector-pseudo-element-case': 'lower',
		'selector-pseudo-element-colon-notation': 'double',
		'selector-pseudo-element-no-unknown': true,
		'selector-root-no-composition': null,
		'selector-type-case': 'lower',
		'selector-type-no-unknown': null,
		'selector-max-empty-lines': [0, { 'severity': 'warning' }],
		'selector-list-comma-newline-after': ['always-multi-line', { 'severity': 'warning' }],
		'selector-list-comma-newline-before': null,
		'selector-list-comma-space-after': ['always-single-line', { 'severity': 'warning' }],
		'selector-list-comma-space-before': ['never', { 'severity': 'warning' }]
	}
};